import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";
import { ThemeProvider } from "@/components/theme-provider"
import { Be_Vietnam_Pro } from "next/font/google";

const be_Vietnam_Pro = Be_Vietnam_Pro({ weight: ['400', '500', '700', '900'], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={be_Vietnam_Pro.className} >
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            disableTransitionOnChange
          >
            <Navbar />
            {children}
          </ThemeProvider>

      </body>
    </html>
  );
}
